 #
# Makefile used to compile shared kernel tricks
 #

BUILDER_TYPE		:= $(BUILDER_TYPE_STCLIB)

BUILDER_HEADER		:=	kernel shared

BUILDER_SOURCE_DIR	:=	init

BUILDER_TARGET		:=	$(TGTSHARED_OVRKRN)

.PHONY: all

include $(MKHELPER_DIR)/builder/builder.mk

all:	lauchbuilder