 #
# Makefile we are using with a build prefix for shared architecture tools
 #

BUILDER_TYPE		:= $(BUILDER_TYPE_STCLIB)

BUILDER_HEADER		:=	AARCH32 shared

BUILDER_SOURCE_DIR	:=	tools

BUILDER_TARGET		:=	$(TGTSHARED_LIBARC)

.PHONY: all

sinclude $(MKHELPER_DIR)/builder/builder.mk

all:	lauchbuilder