 #
# Makefile we are using with a build prefix for shared over the world objects
 #

BUILDER_TYPE		:= $(BUILDER_TYPE_STCLIB)

BUILDER_HEADER		:=	OverTheWorld shared

BUILDER_SOURCE_DIR	:=	lib

BUILDER_TARGET		:=	$(TGTSHARED_OVRWLD)

.PHONY: all

sinclude $(MKHELPER_DIR)/builder/builder.mk

all:	lauchbuilder