 #
# Makefile we are using with a build prefix for shared architecture tools
 #

BUILDER_HEADER			:=	AARCH64 shared

BUILDER_TYPE			:=	$(BUILDER_TYPE_STCLIB)

BUILDER_TARGET			:=	$(TGTSHARED_LIBARC)

BUILDER_SOURCE_DIR		:=	tools

.PHONY: all

sinclude $(MKHELPER_DIR)/builder/builder.mk

all:	lauchbuilder