#!/bin/sh

### Environment ################################################################
MKTOOL=$(realpath $(dirname $0))
SOURCE=$(dirname $(dirname $(realpath $0)))
printf "[\e[36;1mTOOL\e[0m] Toolchain Builder\n"
printf "[\e[34;1mINFO\e[0m] Building from $SOURCE...\n"

### Dependencies ###############################################################
source $MKTOOL/build-helpers

require make
require bc
require bison

unfatalrequire makeinfo
unfatalrequire qemu-system-arm
unfatalrequire qemu-system-aarch64
unfatalrequire source-highlight

### Source GNUARM ##############################################################
run "Dowload gnu ARM toolchain" git submodule update --init --recursive

### We're done! ################################################################
printf "[\e[36;1mTOOL\e[0m] Toolchain built!\n"
