#ifndef _PREPROCESSOR_GENERATION_
#define _PREPROCESSOR_GENERATION_

#define ___GENERATE_ROOT_HEADER_TARGET(TGT)     #TGT
#define __GENERATE_ROOT_HEADER_TARGET(TGT)      ___GENERATE_ROOT_HEADER_TARGET(TGT.h)
#define _GENERATE_ROOT_HEADER_TARGET(BASE, TGT) __GENERATE_ROOT_HEADER_TARGET(BASE/TGT)
#define GENERATE_ROOT_HEADER_TARGET(BASE, TGT)  _GENERATE_ROOT_HEADER_TARGET(BASE, TGT)

#define GENERATE_HEADER_TARGET_COMMON(TGT) GENERATE_ROOT_HEADER_TARGET(TARGET_COMMON_INC, TGT)

#endif